name: on_audio_query
description: Flutter Plugin used to query audios/songs infos [title, artist, album, etc..] from device storage.
version: 2.2.0
homepage: https://github.com/LucasPJS/on_audio_query/tree/main/on_audio_query
# pub.dev: https://pub.dev/packages/on_audio_query
# ========
# author: Lucas Josino
# github: https://github.com/LucasPJS
# website: https://lucasjosino.com/

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  on_audio_query_platform_interface: ^1.0.0
  on_audio_query_web: ^1.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  # Material Design
  uses-material-design: true
  plugin:
    platforms:
      android:
        package: com.lucasjosino.on_audio_query
        pluginClass: OnAudioQueryPlugin
      ios:
        pluginClass: OnAudioQueryPlugin
      web:
        default_package: on_audio_query_web