name: Dart Analyzer
on: [push, pull_request]

jobs:
  package-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: axel-op/dart-package-analyzer@v3
        id: dart_analysis
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          relativePath: on_audio_query/
      - name: Check Scores
        env:
          TOTAL: ${{ steps.dart_analysis.outputs.total }}
          TOTAL_MAX: ${{ steps.dart_analysis.outputs.total_max }}
        run: |
          if (( ($TOTAL + 10) < ($TOTAL_MAX + 10) ))
          then
            echo Total Score: [$TOTAL].
            echo Something's wrong!.
            exit 1
          fi